# MYSQL CONFIGURATION
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanager
    username: root
    password: 1337228
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
